language: python
env:
    global:
    -GH_REF: github.com/dseuss/mpnum.git

notifications:
    email: false

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'

addons:
    apt:
        packages:
            - libhdf5-serial-dev

install:
    - pip install --only-binary=numpy,scipy .
    # install h5py from binaries since setup.py test doesn't
    - pip install --only-binary=h5py h5py
    - pip install coveralls
    - pip freeze

script:
    - travis_wait 10 bash tests/travis.sh
after_success:
    coveralls
